### ISSUE TITLE
LinkCard (29-37) has react errors - see description

### ISSUE THREAD

**Issue by GuyMcKechnie** [Yamure/scientficlinker#18]
- [ ] `useDispatch()` - React Hook "useDispatch" is called conditionally. React Hooks must be called in the exact same order in every component render.eslint[react-hooks/rules-of-hooks](https://reactjs.org/docs/hooks-rules.html)
- [ ] `useSelector` - React Hook "useSelector" is called conditionally. React Hooks must be called in the exact same order in every component render.eslint[react-hooks/rules-of-hooks](https://reactjs.org/docs/hooks-rules.html)
- [ ] `useState` - React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render.eslint[react-hooks/rules-of-hooks](https://reactjs.org/docs/hooks-rules.html)
- [ ] `firstLetter` - 'firstLetter' is declared but its value is never read.ts(6133) & 'firstLetter' is assigned a value but never used.eslint[no-unused-vars](https://eslint.org/docs/latest/rules/no-unused-vars)

**Comment by Yamure** [comment]
fixed in update
