### ISSUE TITLE
you can scroll when the popup for the tool is open. i don't think this is a desired feature

### ISSUE THREAD

**Issue by GuyMcKechnie** [Yamure/scientficlinker#21]

**Comment by Yamure** [comment]
i  fixed that bug where is it still ?  let me check on phone

**Comment by GuyMcKechnie** [comment]
are you merged with main? cause its still hapenning with the deployed version

**Comment by Yamure** [comment]
hebana yes please send a screen recoding its not doing that on my side

**Comment by GuyMcKechnie** [comment]
https://github.com/user-attachments/assets/7eb4b5e3-d081-4284-8bc0-4946f98ddbf3

**Comment by Yamure** [comment]
lol how is this a bug though

**Comment by GuyMcKechnie** [comment]
you shouldnt be able to scroll while the model is open

**Comment by Yamure** [comment]
its been fixed
